import definitions

set_option autoImplicit false

/-!
# Seven external axioms, individually stated and explained

These declarations are unproved assumptions, including the data-valued axioms
A01-A03. Their names express an intended interpretation; the Lean types below
specify exactly what is assumed. No identification with a concrete Sturmian
subshift or topological full group is encoded here.

A01-A05 are permitted for T06. T07 additionally permits A06-A07.
T01-T05 do not depend on these axioms; their verifier permits no project axioms.
-/

namespace CollisionRank
universe u

/--
A01. A named carrier type.

Assume a type named SturmianGroup in Lean's universe zero (`Type`).
This declaration alone supplies neither an element nor any algebraic structure,
cardinality property, or relation to a Sturmian subshift. A02 will supply the
group structure, which in particular supplies an identity element.

Intended external interpretation: the carrier of the derived topological full
group [[T]]' of the two-sided Sturmian subshift with slope [0;2,3,4,...].
That interpretation is not part of this axiom's Lean type.
-/
axiom SturmianGroup : Type

/--
A02. A group structure on the named carrier.

Assume a value of `Group SturmianGroup`: multiplication, identity, inversion,
and the group laws on the type introduced by A01. Register this particular
structure as the typeclass instance used by subsequent statements.
There is no assumption of commutativity, nontriviality, infinitude, finite
generation, simplicity, or amenability. No connection to a concrete full-group
construction is expressed by this axiom.
-/
axiom sturmianGroupStructure : Group SturmianGroup

attribute [instance] sturmianGroupStructure

/--
A03. Symbolic permutation data with uniform bounds and within-point locality.

Assume a value D of `SymbolicOrbitData SturmianGroup`, with both its alphabet
and point type in universe zero. This supplies all the following data and laws:
(a) a finite alphabet with decidable equality and a type Point;
(b) coordinates coord : Point -> Z -> Alphabet;
(c) shifts by integers with coord (shift q x) n = coord x (n+q);
(d) for each x, a group homomorphism g |-> pi_g^x into permutations of Z;
(e) a natural bound D_g for each g such that |pi_g^x(n)-n| <= D_g for all x,n;
(f) a natural radius rho_g for each g such that, within any one point x,
    coord x (m+t) = coord x (n+t) for every integer |t| <= rho_g implies
    pi_g^x(m)-m = pi_g^x(n)-n, for all m,n.

All fields, including their law proofs, are supplied as unproved data by this
axiom. The bound and radius depend on g and are uniform in the other variables.
No cross-point locality, faithfulness, shift-action laws beyond the displayed
coordinate equation, permutation covariance under shifts, topology, minimality,
aperiodicity, or identification of points by their coordinates is assumed.
The point type is not required to be nonempty by this axiom alone.
The alphabet is not required to have exactly two symbols.
-/
axiom sturmianRealization : SymbolicOrbitData.{0, 0, 0} SturmianGroup

/--
A04. Local finiteness of every nonnegative-half-line stabilizer.

Assume that for every point x supplied by A03 and every finite subset C of the
named group, if every g in C preserves the nonnegative integers setwise under
pi_g^x, then the subgroup generated by C in the whole named group has a finite
carrier. Setwise preservation here means: for every integer n,
0 <= pi_g^x(n) if and only if 0 <= n.

The point x and finite subset C are universally quantified. C may be empty.
The claim is not that the entire stabilizer is finite, and not that its elements
fix each nonnegative integer individually. The passage from the cited ambient
full-group stabilizer theorem to the intended derived subgroup is external;
it is not proved by this axiom.

Source for the intended interpretation:
[On Algebraic Properties of Topological Full Groups](https://arxiv.org/pdf/1105.0719),
Definition 2.1 and Theorem 2.2(2).
-/
axiom sturmianHalfLineLocalFinite :
  ∀ (x : sturmianRealization.Point) (C : Finset SturmianGroup),
    (∀ g ∈ C, g ∈ sturmianRealization.halfLineStabilizer x) →
    Finite ↥(Subgroup.closure (↑C : Set SturmianGroup))

/--
A05. Arbitrarily high exponent-scaled periodic windows.

Assume that for every natural E >= 1 there exist a point x of A03, a natural
period p >= 1, and an integer a such that, for any two integers i,j in the closed
interval [a,a+p*E-1], congruence i = j modulo p implies coord x i = coord x j.
Thus the interval has exactly p*E integer positions.

The point, period, and starting position may all depend on E. A common point or
period for all E is not asserted, p need not be the least period, and no global
periodicity of x is asserted. This axiom does imply existence of a point (take
E=1). The construction from the specified Sturmian language is external.

Sources for the standard-word construction:
[Characterization of Repetitions in Sturmian Words: A New Proof](https://arxiv.org/pdf/1411.5474),
Section 3 (the recurrence and nested-prefix property), and
[Powers in Sturmian sequences](https://doi.org/10.1016/S0195-6698(03)00026-X).
-/
axiom sturmianScaledPeriodicWindow :
  ∀ E : ℕ, 1 ≤ E →
    ∃ (x : sturmianRealization.Point) (p : ℕ) (a : ℤ),
      1 ≤ p ∧
      PeriodicOn sturmianRealization.coord x p a
        (a + (p : ℤ) * (E : ℤ) - 1)

/--
A06. An opaque predicate on groups.

Assume a universe-polymorphic assignment of a proposition `InSG G` to every
type G equipped with a group structure. The chosen group structure is an
argument, so no independence from that choice is stipulated.
No defining properties, closure properties, isomorphism invariance, examples,
or nonexamples are included in this axiom.

Intended external interpretation: membership in the class of subexponentially
amenable groups, called SG here and also known as SAG in the literature.
The Lean declaration does not define that class or ensure this interpretation.

Source for the intended class:
[On Algebraic Properties of Topological Full Groups](https://arxiv.org/pdf/1105.0719),
Section 2, the definition of SAG immediately before Proposition 2.4.
-/
axiom InSG (G : Type u) [Group G] : Prop

/--
A07. Nonmembership of the named group in the opaque predicate.

Assume that `InSG SturmianGroup` is false, using the group structure from A02
and the predicate from A06. Equivalently, any proof of that proposition leads
to False. This directly supplies the desired nonmembership statement for the
named witness; the Lean development does not derive it from a definition of SG
or from a formalization of the corresponding external nonmembership theorem.

The intended claim that the actual Sturmian derived full group is outside the
actual class of subexponentially amenable groups uses both external
identifications as well as the cited literature result.

Source for the intended nonmembership result:
[On Algebraic Properties of Topological Full Groups](https://arxiv.org/pdf/1105.0719),
Proposition 2.4.
-/
axiom sturmian_not_in_SG : ¬ InSG SturmianGroup

end CollisionRank
